sudo: required

language: node_js
node_js:
  - 12.13.1
services:
  - docker

before_install:
  - docker build -t hamlet/docker-react -f Dockerfile.dev .

script:
  - docker run hamlet/docker-react  npm run test -- --coverage
