sudo: required

services:
  - docker

before_install:
  - docker build -t hamlet/docker-react -f Dockerfile.dev .

script:
  - docker run hamlet/docker-react  npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker"
  env: "Docker-env"
  bucket_name:
  bucket_path: "docker"
  on:
    branch: master

